name: SonataDiagnostic
options:
  bundleIdPrefix: com.redhadjane
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    MARKETING_VERSION: "0.2.0"
    CURRENT_PROJECT_VERSION: "2"
targets:
  SonataDiagnostic:
    type: application
    platform: iOS
    sources:
      - SonataDiagnostic
    info:
      path: SonataDiagnostic/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.redhadjane.sonatadiagnostic
        PRODUCT_NAME: SonataDiagnostic
        TARGETED_DEVICE_FAMILY: "1"
        GENERATE_INFOPLIST_FILE: NO
