import SwiftUI

struct NativeEmployees:View {
    @EnvironmentObject var store:NativeStore
    @State private var search="",selected:J?,editing:J?
    var people:[J] {store.employees.filter {search.isEmpty || $0.displayName.localizedCaseInsensitiveContains(search)}}
    var body:some View {HStack(spacing:0) {List(selection:Binding(get:{selected?.id},set:{id in selected=people.first {$0.id == id}})) {ForEach(people) {person in HStack {PersonMark(name:person.displayName);VStack(alignment:.leading,spacing:5) {Text(person.displayName).font(.headline);Text(person["role"].text.capitalized+" · "+person.statusText).font(.caption).foregroundStyle(.secondary)}}.padding(.vertical,6).tag(person.id)}}.searchable(text:$search,prompt:"Find employee").frame(minWidth:250,idealWidth:310,maxWidth:360)
        if let person=selected {ScrollView {VStack(spacing:20) {HOPPanel {HStack {PersonMark(name:person.displayName);VStack(alignment:.leading){Text(person.displayName).font(.largeTitle.bold());Text(([person["role"].text]+person["secondary_roles"].array.map(\.text)).joined(separator:" · ").capitalized).foregroundStyle(.secondary)};Spacer();Button("Edit profile"){editing=person}.buttonStyle(.borderedProminent)};NativeRecordSummary(record:person,fields:["full_name","phone","email","status","employee_type"])};HOPPanel(title:"Published shifts",subtitle:"Week of \(HOPDay.label(store.week))") {let schedule=store.schedule("published");let shifts=schedule["entries"].array.filter {$0["employee_id"].text == person.id};if shifts.isEmpty {Text("No published shifts this week").foregroundStyle(.secondary)};ForEach(shifts) {entry in let row=schedule["rows"].array.first {$0.id == entry["row_id"].text};DetailPair(title:HOPDay.label(HOPDay.add(store.week,(entry["day_of_week"].int-2+7)%7)),value:"\(row?["label"].text ?? "Shift") · \(String(entry["start_time"].text.prefix(5)))–\(String(entry["end_time"].text.prefix(5)))")}};Button("Open availability"){store.module = .availability}.buttonStyle(.bordered)}.padding(24)}}else {NativeEmpty(title:"Choose an employee",detail:"Contact information, role pay and published shifts in one place.",icon:"person.crop.rectangle")}
    }.toolbar {Button {editing = .object(["id":.s("new"),"role":.s("waitress"),"status":.s("active"),"employee_type":.s("part")])} label:{Label("Add employee",systemImage:"person.badge.plus")}}.sheet(item:$editing){NativeEmployeeEditor(original:$0)}.onChange(of:store.employees){_,values in if let id=selected?.id {selected=values.first {$0.id == id}}} }
}
struct NativeEmployeeEditor:View {
    @EnvironmentObject var store:NativeStore;@Environment(\.dismiss) var dismiss
    var original:J
    @State private var person:J = .null,pin="",visible=false,pinInfo="",confirmDelete=false
    let roles=["waitress","host","floor","manager","kitchen","driver","other"]
    var body:some View {NavigationStack {Form {
        Section("Profile") {RecordFields(record:$person,fields:[.init(key:"display_name",title:"Display name"),.init(key:"full_name",title:"Full name"),.init(key:"role",title:"Primary role",kind:.choice(roles)),.init(key:"status",title:"Status",kind:.choice(["active","inactive","on_leave","terminated"])),.init(key:"employee_type",title:"Employment",kind:.choice(["part","full","seasonal","temporary"])),.init(key:"phone",title:"Phone"),.init(key:"email",title:"Email")])}
        Section("Approved additional roles") {ForEach(roles.filter {$0 != person["role"].text},id:\.self) {role in Toggle(role.capitalized,isOn:Binding(get:{person["secondary_roles"].array.contains(.s(role))},set:{on in var values=person["secondary_roles"].array.filter {$0 != .s(role)};if on {values.append(.s(role))};person["secondary_roles"] = .array(values)}))}}
        Section("Hourly pay by role") {ForEach(roles.filter {$0 == person["role"].text || person["secondary_roles"].array.contains(.s($0))},id:\.self){role in LabeledContent(role.capitalized) {TextField("Use default",text:Binding(get:{person["role_pay_rates"][role].isNull ? "" : HOPMoney.dollars(person["role_pay_rates"][role].int)},set:{var rates=person["role_pay_rates"];rates[role] = $0.isEmpty ? .null : .n(HOPMoney.cents($0));person["role_pay_rates"]=rates})).keyboardType(.decimalPad).multilineTextAlignment(.trailing)}};RecordFields(record:$person,fields:[.init(key:"pay_rate_cents",title:"Default hourly rate",kind:.money)])}
        Section("Account security") {HStack {if visible {TextField("New PIN (blank keeps current)",text:$pin)}else {SecureField("New PIN (blank keeps current)",text:$pin)};Button {visible.toggle()}label:{Image(systemName:visible ? "eye.slash" : "eye")}.buttonStyle(.borderless).accessibilityLabel(visible ? "Hide new PIN" : "Reveal new PIN")}.keyboardType(.numberPad);if original.id != "new" {Button("Check existing PIN"){Task {do {let value=try await store.api.request("/api/employees/\(original.id)?include_sensitive=true");let employee=value["employee"];pinInfo=employee["pin_configured"].truth ? "PIN configured. Last four: \(employee["pin_last4"].text). A hashed PIN cannot be fully recovered." : "No PIN configured."}catch {store.report(error)}}};if !pinInfo.isEmpty {Text(pinInfo).font(.footnote)}}}
        if original.id != "new" {Section {Button("Delete employee",role:.destructive){confirmDelete=true};Text("The server decides whether existing employee history requires deactivation instead.").font(.footnote).foregroundStyle(.secondary)}}
    }.navigationTitle(original.id == "new" ? "Add employee" : "Edit employee").toolbar {ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Save"){save()}.bold().disabled(store.saving || person["display_name"].text.isEmpty || person["full_name"].text.isEmpty)}}.task {person=original}
    .confirmationDialog("Delete \(original.displayName)? This affects the shared employee record.",isPresented:$confirmDelete,titleVisibility:.visible){Button("Delete employee",role:.destructive){Task {do {_ = try await store.send("/api/employees/\(original.id)",method:"DELETE");await store.load();dismiss()}catch {store.report(error)}}}}
    } }
    func save() {if !pin.isEmpty && (pin.count<4 || pin.count>8 || !pin.allSatisfy(\.isNumber)){store.error="PIN must contain 4–8 digits.";return};Task {do {var payload=person;if !pin.isEmpty {payload["pin"] = .s(pin)};let fresh=original.id == "new";_ = try await store.send(fresh ? "/api/employees" : "/api/employees/\(original.id)",method:fresh ? "POST" : "PUT",body:payload);pin="";await store.load();dismiss()}catch {store.report(error)}}}
}
struct NativeAvailability:View {
    @EnvironmentObject var store:NativeStore
    @State private var filter="All",selected:J?,search=""
    var people:[J] {let ids=Set(store.schedule("published")["entries"].array.map {$0["employee_id"].text});return store.employees.filter {($0["status"].text == "active") && (filter == "All" || ids.contains($0.id)) && (search.isEmpty || $0.displayName.localizedCaseInsensitiveContains(search))}}
    var body:some View {NativeScreen(title:"Availability",subtitle:"All employees or the published week's team. Green is available, red is off, gray means not submitted.") {WeekControl();HStack {Picker("Team",selection:$filter){Text("All employees").tag("All");Text("Week team").tag("Team")}.pickerStyle(.segmented).frame(maxWidth:380);TextField("Find employee",text:$search).textFieldStyle(.roundedBorder)};ScrollView(.horizontal) {VStack(spacing:0) {HStack {Text("Employee").frame(width:170,alignment:.leading);ForEach(HOPDay.days(store.week),id:\.self){day in Text(HOPDay.label(day,"EEE d")).frame(width:105)}}.font(.subheadline.bold()).padding(.vertical);ForEach(people){person in Button {selected=person} label:{HStack(spacing:0){Text(person.displayName).font(.headline).frame(width:170,alignment:.leading);ForEach(HOPDay.days(store.week),id:\.self){day in HStack(spacing:3){ForEach(["AM","PM"],id:\.self){shift in let found=store.available.first {$0["employee_id"].text == person.id && $0["day"].text.lowercased().prefix(3) == HOPDay.label(day,"EEE").lowercased() && $0["shift_key"].text == shift};let color:Color=found == nil ? .gray : found?["status"].text == "off" ? .red : HOPStyle.green;Text(shift).font(.caption.bold()).frame(width:47,height:44).foregroundStyle(color).background(color.opacity(0.13),in:RoundedRectangle(cornerRadius:8))}}.frame(width:105)}}.padding(.vertical,5).contentShape(Rectangle())}.buttonStyle(.plain)}}}.padding().background(.background,in:RoundedRectangle(cornerRadius:20))}.sheet(item:$selected){NativeAvailabilityEditor(employee:$0,week:store.week)} }
}
struct NativeAvailabilityEditor:View {
    @EnvironmentObject var store:NativeStore;@Environment(\.dismiss) var dismiss
    var employee:J;var week:String
    @State private var payload:J = .null,unlock=false,busy=true
    var path:String {"/api/availability/employee/\(employee.id)"}
    var body:some View {NavigationStack {Form {Section {Text(employee.displayName).font(.title2.bold());Text("Week of \(HOPDay.label(week))");if busy {ProgressView()};if payload["locked"].truth {Label("Confirmed / locked",systemImage:"lock.fill");Button("Unlock for editing"){unlock=true}}};Section("Tap a cell to switch") {ForEach(Array(payload["availability"].array.enumerated()),id:\.offset){i,slot in Button {var slots=payload["availability"].array;slots[i]["status"] = .s(slot["status"].text == "off" ? "available" : "off");payload["availability"] = .array(slots)} label:{HStack {Text(slot["day"].text.capitalized).font(.headline);Text(slot["shift_key"].text);Spacer();StatusTag(value:slot["status"].text)}}.disabled(payload["locked"].truth || busy)}}}.navigationTitle("Quick availability").toolbar {ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Save"){Task {do {_ = try await store.send(path+"/save",body:.object(["week_start":.s(week),"slots":payload["availability"]]));await store.load();dismiss()}catch {store.report(error)}}}.disabled(busy || payload.isNull || payload["locked"].truth || store.saving)}}.task {await load()}.confirmationDialog("Unlock \(employee.displayName)'s confirmed availability?",isPresented:$unlock,titleVisibility:.visible){Button("Unlock"){Task {do {_ = try await store.send(path+"/unlock",body:.object(["week_start":.s(week),"unlocked_by":.s(store.manager.id)]));await load()}catch {store.report(error)}}}}} }
    func load() async {busy=true;defer {busy=false};do {payload=try await store.api.request(path+"?week_start=\(week)")}catch {store.report(error)}}
}
struct NativeInbox:View {
    @EnvironmentObject var store:NativeStore
    @State private var tab="pending",selected:J?
    var requests:[J] {store.items("/api/inbox/\(tab)","requests","items")}
    var body:some View {NativeScreen(title:"Requests & approvals",subtitle:"Employee, request type, dates and conflicts—visible before you open a record.") {Picker("Queue",selection:$tab){Text("Pending").tag("pending");Text("History").tag("history")}.pickerStyle(.segmented).frame(maxWidth:350);if requests.isEmpty {NativeEmpty(title:"No \(tab) requests",icon:"tray")};ForEach(requests){request in Button {selected=request}label:{HOPPanel {HStack {PersonMark(name:request.first("employee_name","name").isEmpty ? store.name(request["employee_id"].text) : request.first("employee_name","name"));VStack(alignment:.leading,spacing:5){Text(request.first("employee_name","name").isEmpty ? store.name(request["employee_id"].text) : request.first("employee_name","name")).font(.headline);Text(request.first("type","request_type").replacingOccurrences(of:"_",with:" ").capitalized+" · "+request.first("start_date","date")).foregroundStyle(.secondary);Text(request.first("note","message")).lineLimit(2)};Spacer();StatusTag(value:request.statusText);Image(systemName:"chevron.right")}}.foregroundStyle(.primary)}.buttonStyle(.plain)}}.sheet(item:$selected){NativeRequestReview(request:$0)} }
}
struct NativeRequestReview:View {
    @EnvironmentObject var store:NativeStore;@Environment(\.dismiss) var dismiss;var request:J
    @State private var note="",pin="",action="",confirm=false,failure=""
    var body:some View {NavigationStack {Form {Section {NativeRecordSummary(record:request,fields:["employee_name","type","start_date","end_date","note","status"])};Section("Dates & conflicts"){ForEach(request["items"].array){item in VStack(alignment:.leading,spacing:8){Text(item.first("item_date","date")).font(.headline);StatusTag(value:item.statusText);ForEach(item["conflict_hints"].array.map(\.text),id:\.self){Text($0).font(.callout).foregroundStyle(.orange)}}}};if request.statusText == "pending" {Section("Manager review"){TextField("Note to employee",text:$note,axis:.vertical);SecureField("Your PIN for conflict override",text:$pin).keyboardType(.numberPad);Text("PIN verification is performed by the server for the signed-in manager. Overlapping shifts remain protected.").font(.footnote).foregroundStyle(.secondary);HStack {Button("Deny",role:.destructive){action="deny";confirm=true}.buttonStyle(.bordered);Spacer();Button("Approve"){action="approve";confirm=true}.buttonStyle(.borderedProminent)}.disabled(store.saving)}};if !failure.isEmpty {ErrorNote(text:failure)}}.navigationTitle("Request details").toolbar {Button("Done"){dismiss()}}.confirmationDialog("\(action.capitalized) this employee request?",isPresented:$confirm,titleVisibility:.visible){Button(action.capitalized){Task {do {_ = try await store.send("/api/requests/\(request.id)/\(action)",body:.object(["manager_note":.s(note),"manager_pin":.s(pin)]));pin="";await store.load();dismiss()}catch {pin="";failure=error.localizedDescription}}}}} }
}
struct NativeApplications:View {
    @EnvironmentObject var store:NativeStore
    @State private var selected:J?,export:NativeDocument?
    let fields=["full_name","phone","email","positions_applied_for","start_date","weekend_available","restaurant_experience","experience_notes","availability","applicant_notes","manager_notes","status"]
    var body:some View {NativeScreen(title:"Applications",subtitle:"Review candidates and export a clean, portrait application copy.") {ForEach(store.items("/api/job-applications","applications")){item in HOPPanel {HStack {PersonMark(name:item.displayName);VStack(alignment:.leading){Text(item.displayName).font(.title3.bold());Text(item["positions_applied_for"].array.map(\.text).joined(separator:", ")).foregroundStyle(.secondary)};Spacer();StatusTag(value:item.statusText)};NativeRecordSummary(record:item,fields:["phone","email","start_date"]);HStack {Button("Review"){selected=item}.buttonStyle(.borderedProminent);Button("Preview / export"){export=NativePDF.record(item,title:"Job application",fields:fields)}.buttonStyle(.bordered)}}}}.sheet(item:$selected){item in NativeRecordEditor(record:item,title:item.displayName,path:"/api/job-applications/\(item.id)",method:"PATCH",fields:[.init(key:"status",title:"Stage",kind:.choice(["new","reviewing","interview","hired","rejected"])),.init(key:"manager_notes",title:"Manager notes",kind:.paragraph)])}.sheet(item:$export){NativeDocumentPreview(document:$0)} }
}
