import SwiftUI

struct NativeMenu:View {
    @EnvironmentObject var store:NativeStore
    @State private var search=""
    @State private var selected:J?
    var body:some View {NativeScreen(title:"Menu",subtitle:"Connected menu items and the existing picture library.") {HStack {TextField("Search menu",text:$search).textFieldStyle(.roundedBorder);Button {selected = .object(["id":.s("new"),"is_active":.bool(true),"price":.number(0)])}label:{Label("Add item",systemImage:"plus")}.buttonStyle(.borderedProminent)};LazyVGrid(columns:[GridItem(.adaptive(minimum:280))],spacing:16){ForEach(store.items("/api/menu/items","items","menu_items").filter {search.isEmpty || $0["name"].text.localizedCaseInsensitiveContains(search)}){item in Button {selected=item}label:{HOPPanel {HStack {NativePhoto(path:item["image_url"].text,size:80);VStack(alignment:.leading,spacing:8){Text(item["name"].text).font(.headline);Text(HOPMoney.show(HOPMoney.round(item["price"].number*100))).foregroundStyle(HOPStyle.green);Text(item["is_active"].truth ? "Available" : "Hidden").font(.caption).foregroundStyle(.secondary)}}}.foregroundStyle(.primary)}.buttonStyle(.plain)}}}.sheet(item:$selected){NativeMenuEditor(original:$0)} }
}
struct NativeMenuEditor:View {
    @EnvironmentObject var store:NativeStore;@Environment(\.dismiss) var dismiss;var original:J
    @State private var item:J = .null
    @State private var pictures=false
    var body:some View {NavigationStack {Form {Section {HStack {NativePhoto(path:item["image_url"].text,size:130);Button("Choose picture"){pictures=true}.disabled(original.id == "new")};if original.id == "new" {Text("Save the new item first to attach a photo.").font(.footnote)}};Section {RecordFields(record:$item,fields:[.init(key:"name",title:"Item name"),.init(key:"description",title:"Description",kind:.paragraph),.init(key:"price",title:"Base price ($)",kind:.number),.init(key:"is_active",title:"Available",kind:.toggle)]);Picker("Category",selection:Binding(get:{item["category_id"].text},set:{item["category_id"] = .s($0)})){Text("Choose category").tag("");ForEach(store.items("/api/menu/categories","categories")){Text($0["name"].text).tag($0.id)}}};if !item["size_prices"].object.isEmpty {Section("Size prices ($)") {ForEach(item["size_prices"].object.keys.sorted(),id:\.self){key in LabeledContent(key.capitalized){NativeNumberField("Price",text:Binding(get:{item["size_prices"][key].text},set:{var sizes=item["size_prices"];sizes[key] = .number(Double($0) ?? 0);item["size_prices"]=sizes})).keyboardType(.decimalPad).multilineTextAlignment(.trailing)}}}}}.navigationTitle("Menu item").toolbar {ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Save"){Task {do {let new=original.id == "new";_ = try await store.send(new ? "/api/menu/items" : "/api/menu/items/\(original.id)",method:new ? "POST" : "PATCH",body:item);await store.load();dismiss()}catch {store.report(error)}}}.disabled(store.saving || item["name"].text.isEmpty || item["category_id"].text.isEmpty)}}.task {item=original}.sheet(isPresented:$pictures){NativeMediaPicker(target:"menu_item_image",menuID:original.id){item["image_url"] = .s($0)}}} }
}
struct NativeClub:View {
    @EnvironmentObject var store:NativeStore
    @State private var tab="Members"
    @State private var search=""
    @State private var member:J?
    @State private var reward:J?
    @State private var campaign=false
    var body:some View {NativeScreen(title:"HOP Club",subtitle:"Real members, balances, pictured rewards and customer campaigns.") {Picker("Section",selection:$tab){ForEach(["Members","Rewards","Campaigns"],id:\.self){Text($0)}}.pickerStyle(.segmented).frame(maxWidth:550)
        if tab == "Members" {TextField("Search member",text:$search).textFieldStyle(.roundedBorder);ForEach(store.items("/api/hopclub/admin/customers","customers","members").filter {search.isEmpty || $0.displayName.localizedCaseInsensitiveContains(search)}){customer in Button {member=customer}label:{HOPPanel {HStack {PersonMark(name:customer.displayName);VStack(alignment:.leading,spacing:6){Text(customer.displayName).font(.headline);Text(customer.first("member_code","phone")).foregroundStyle(.secondary)};Spacer();Text("\(customer["points_balance"].text) pts").font(.title3.bold());Image(systemName:"chevron.right")}}.foregroundStyle(.primary)}.buttonStyle(.plain)}}
        else if tab == "Rewards" {Button {reward = .object(["id":.s("new"),"is_active":.bool(true),"trigger_type":.s("point_threshold"),"points_required":.n(100),"visits_required":.n(10)])}label:{Label("New reward",systemImage:"plus")}.buttonStyle(.borderedProminent);LazyVGrid(columns:[GridItem(.adaptive(minimum:320))],spacing:16){ForEach(store.items("/api/hopclub/admin/reward-rules","reward_rules","rules","rewards")){rule in Button {reward=rule}label:{HOPPanel {HStack {NativePhoto(path:rule["image_url"].text,size:100);VStack(alignment:.leading,spacing:8){Text(rule["title"].text).font(.headline);Text(rule["trigger_type"].text == "visit_count" ? "\(rule["visits_required"].text) purchases" : "\(rule["points_required"].text) points").foregroundStyle(HOPStyle.green);StatusTag(value:rule["is_active"].truth ? "Active" : "Hidden")}}}.foregroundStyle(.primary)}.buttonStyle(.plain)}}}
        else {Button {campaign=true}label:{Label("Create campaign",systemImage:"megaphone")}.buttonStyle(.borderedProminent);ForEach(store.items("/api/hopclub/campaigns","campaigns")){item in HOPPanel {Text(item["title"].text).font(.headline);Text(item.first("body","message"));StatusTag(value:item.statusText);DetailPair(title:"Scheduled",value:item["schedule_at"].text)}}}
    }.sheet(item:$member){NativeMemberEditor(original:$0)}.sheet(item:$reward){NativeRewardEditor(original:$0)}.sheet(isPresented:$campaign){NativeCampaignEditor()} }
}
struct NativeMemberEditor:View {
    @EnvironmentObject var store:NativeStore;@Environment(\.dismiss) var dismiss;var original:J
    @State private var member:J = .null
    @State private var delta=""
    @State private var reason=""
    @State private var confirm=false
    var body:some View {NavigationStack {Form {Section("Customer") {RecordFields(record:$member,fields:[.init(key:"name",title:"Name"),.init(key:"phone",title:"Phone"),.init(key:"username",title:"Username")]);DetailPair(title:"Points balance",value:original["points_balance"].text);DetailPair(title:"Member code",value:original["member_code"].text)};Section("Audited point adjustment") {TextField("Points to add or remove",text:$delta).keyboardType(.numbersAndPunctuation);TextField("Required reason",text:$reason);Button("Apply adjustment"){confirm=true}.disabled(Int(delta) == nil || Int(delta) == 0 || reason.trimmingCharacters(in:.whitespaces).isEmpty || store.saving)}}.navigationTitle("Member profile").toolbar {ToolbarItem(placement:.cancellationAction){Button("Done"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Save profile"){Task {do {_ = try await store.send("/api/hopclub/admin/customers/\(original.id)",method:"PATCH",body:member.set(["reason":.s("Manager updated profile from native iPad")]));await store.load();dismiss()}catch {store.report(error)}}}.disabled(store.saving)}}.task {member=original}.confirmationDialog("Adjust this member's balance by \(delta) points?",isPresented:$confirm,titleVisibility:.visible){Button("Apply adjustment"){Task {do {_ = try await store.send("/api/hopclub/admin/customers/\(original.id)/points-adjustment",body:.object(["delta":.n(Int(delta) ?? 0),"reason":.s(reason)]));await store.load();dismiss()}catch {store.report(error)}}}}} }
}
struct NativeRewardEditor:View {
    @EnvironmentObject var store:NativeStore;@Environment(\.dismiss) var dismiss;var original:J
    @State private var rule:J = .null
    @State private var pictures=false
    var body:some View {NavigationStack {Form {Section {HStack {NativePhoto(path:rule["image_url"].text,size:180);Button("Choose reward picture"){pictures=true}}};Section {RecordFields(record:$rule,fields:[.init(key:"title",title:"Reward title"),.init(key:"code",title:"Internal code"),.init(key:"description",title:"Description",kind:.paragraph),.init(key:"trigger_type",title:"Earned by",kind:.choice(["point_threshold","visit_count"])),.init(key:"points_required",title:"Points required",kind:.number),.init(key:"visits_required",title:"Purchases required",kind:.number),.init(key:"is_active",title:"Visible to customers",kind:.toggle),.init(key:"reason",title:"Change reason")])}}.navigationTitle("Reward").toolbar {ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Save"){Task {do {var payload=rule;if original.id == "new" {payload["id"] = .null};_ = try await store.send("/api/hopclub/admin/reward-rules",body:payload);await store.load();dismiss()}catch {store.report(error)}}}.disabled(store.saving || rule["title"].text.isEmpty || rule["code"].text.isEmpty || rule["reason"].text.isEmpty)}}.task {rule=original}.sheet(isPresented:$pictures){NativeMediaPicker(target:"reward_image"){rule["image_url"] = .s($0)}}} }
}
struct NativeCampaignEditor:View {
    @EnvironmentObject var store:NativeStore;@Environment(\.dismiss) var dismiss
    @State private var campaign:J = .object(["audience":.s("all_members"),"repeat_rule":.s("once"),"send_now":.bool(false)])
    @State private var schedule=false
    @State private var date=Date()
    @State private var confirm=false
    var body:some View {NavigationStack {Form {Section {RecordFields(record:$campaign,fields:[.init(key:"title",title:"Campaign title"),.init(key:"body",title:"Message",kind:.paragraph),.init(key:"audience",title:"Audience",kind:.choice(["all_members","vip","inactive_30d"])),.init(key:"reason",title:"Manager reason")])};Section("Delivery") {Toggle("Schedule for later",isOn:$schedule);if schedule {DatePicker("Send at",selection:$date,in:Date()...);RecordFields(record:$campaign,fields:[.init(key:"repeat_rule",title:"Repeat",kind:.choice(["once","daily","weekly"]))])};Text("Delivery uses the connected HOP Club campaign service.").font(.footnote).foregroundStyle(.secondary)}}.navigationTitle("Customer campaign").toolbar {ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button(schedule ? "Schedule" : "Send now"){confirm=true}.disabled(store.saving || campaign["title"].text.isEmpty || campaign["body"].text.isEmpty || campaign["reason"].text.isEmpty)}}.confirmationDialog(schedule ? "Schedule this campaign for customers?" : "Send this campaign to customers now?",isPresented:$confirm,titleVisibility:.visible){Button("Confirm delivery"){Task {do {var payload=campaign;payload["send_now"] = .bool(!schedule);payload["schedule_at"] = schedule ? .s(ISO8601DateFormatter().string(from:date)) : .null;_ = try await store.send("/api/hopclub/campaigns",body:payload);await store.load();dismiss()}catch {store.report(error)}}}}} }
}
struct NativeNotifications:View {
    @EnvironmentObject var store:NativeStore
    @State private var selected:J?
    @State private var compose=false
    var body:some View {NativeScreen(title:"Notifications",subtitle:"In-app manager updates. Staff delivery is handled by your existing HOP notification service.") {HStack {StatusTag(value:"\(store.unread) unread");Spacer();Button {compose=true}label:{Label("Notify staff",systemImage:"paperplane")}.buttonStyle(.borderedProminent)};ForEach(store.notifications){item in Button {selected=item}label:{HOPPanel {HStack {Image(systemName:item["read_at"].isNull ? "bell.badge.fill" : "bell").foregroundStyle(HOPStyle.teal).font(.title2);VStack(alignment:.leading,spacing:6){Text(smartTitle(item)).font(.headline);Text(item.first("message","body")).foregroundStyle(.secondary).lineLimit(3)};Spacer();Image(systemName:"chevron.right")}}.foregroundStyle(.primary)}.buttonStyle(.plain)};if store.notifications.isEmpty {NativeEmpty(title:"You're caught up",icon:"bell")}}.sheet(item:$selected){item in NavigationStack {Form {Section {Text(smartTitle(item)).font(.title2.bold());Text(item.first("message","body"));NativeRecordSummary(record:item,fields:["category","created_at","audience"])};Section {Button("Mark read"){Task {do {_ = try await store.send("/api/notifications/\(item.id)/read");await store.load();selected=nil}catch {store.report(error)}}};if item["category"].text.contains("request") || item["title"].text.lowercased().contains("request") {Button("Open employee requests"){selected=nil;store.module = .inbox}}}}.navigationTitle("Notification").toolbar {Button("Done"){selected=nil}}}}.sheet(isPresented:$compose){NativeStaffMessage()} }
    private func smartTitle(_ item:J)->String {let title=item["title"].text;if title.lowercased() == "new employee request" {let message=item.first("message","body");return message.isEmpty ? title : String(message.prefix(110))};return title}
}
struct NativeStaffMessage:View {
    @EnvironmentObject var store:NativeStore;@Environment(\.dismiss) var dismiss
    @State private var message:J = .object(["audience":.s("all_staff"),"category":.s("announcement")])
    @State private var confirm=false
    var body:some View {NavigationStack {Form {RecordFields(record:$message,fields:[.init(key:"title",title:"Title"),.init(key:"message",title:"Message",kind:.paragraph),.init(key:"audience",title:"Recipients",kind:.choice(["all_staff","manager","employee"]))]);if message["audience"].text == "employee" {Picker("Employee",selection:Binding(get:{message["employee_id"].text},set:{message["employee_id"] = .s($0)})){Text("Select employee").tag("");ForEach(store.employees){Text($0.displayName).tag($0.id)}}};Text("This sends immediately. Background delivery depends on each staff device's existing push permissions.").font(.footnote).foregroundStyle(.secondary)}.navigationTitle("Notify staff").toolbar {ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("Send"){confirm=true}.disabled(store.saving || message["title"].text.isEmpty || message["message"].text.isEmpty || (message["audience"].text == "employee" && message["employee_id"].text.isEmpty))}}.confirmationDialog("Send this staff notification now?",isPresented:$confirm,titleVisibility:.visible){Button("Send notification"){Task {do {_ = try await store.send("/api/notifications",body:message);await store.load();dismiss()}catch {store.report(error)}}}}} }
}
struct NativeWebsite:View {
    @EnvironmentObject var store:NativeStore
    @State private var content:J = .null
    @State private var identity:J = .null
    @State private var hero:J = .null
    @State private var confirm=false
    var body:some View {Form {Section("Public website") {Link(destination:URL(string:CommandPolicy.origin)!) {Label("Open public website",systemImage:"globe")};Text("Native editing of restaurant identity and the home hero. Changes below affect the public site.").foregroundStyle(.secondary)};Section("Restaurant identity"){RecordFields(record:$identity,fields:[.init(key:"restaurantName",title:"Restaurant"),.init(key:"phone",title:"Phone"),.init(key:"email",title:"Email"),.init(key:"addressLine1",title:"Address"),.init(key:"addressLine2",title:"City / ZIP"),.init(key:"footerDescription",title:"Footer text",kind:.paragraph)])};Section("Home hero"){RecordFields(record:$hero,fields:[.init(key:"eyebrow",title:"Eyebrow"),.init(key:"headlineBefore",title:"Headline before"),.init(key:"highlight",title:"Highlighted word"),.init(key:"headlineAfter",title:"Headline after"),.init(key:"description",title:"Description",kind:.paragraph)])};Button("Save website changes"){confirm=true}.disabled(content.isNull || store.saving)}.task(id:store.data["/api/website-content"]){let value=store.data["/api/website-content"] ?? .null;content=value["content"].isNull ? value : value["content"];identity=content["identity"];hero=content["home"]["hero"]}.confirmationDialog("Update the public website?",isPresented:$confirm,titleVisibility:.visible){Button("Save website"){Task {do {var value=content;value["identity"]=identity;var home=value["home"];home["hero"]=hero;value["home"]=home;_ = try await store.send("/api/website-content",method:"PUT",body:value);await store.load()}catch {store.report(error)}}}} }
}
struct NativeSettings:View {
    @EnvironmentObject var store:NativeStore
    @AppStorage("hop.ipad.theme") private var theme="system"
    @AppStorage("hop.ipad.sound") private var sound=true
    @State private var profile:J = .null
    @State private var notification:J = .null
    var body:some View {Form {Section("iPad appearance") {Picker("Theme",selection:$theme){Text("System").tag("system");Text("Light").tag("light");Text("Dark").tag("dark")}.onChange(of:theme){_,value in store.theme=value};Text("Text size follows iPad Settings → Display & Brightness → Text Size. Reduced Motion follows Accessibility settings.").font(.footnote).foregroundStyle(.secondary)};Section("Notifications on this iPad") {Toggle("Sound for new in-app alerts",isOn:$sound);Text("In-app alerts refresh while this app is active. Free-account SideStore signing does not enable APNs background push for this manager app.").font(.footnote).foregroundStyle(.secondary)};Section("Restaurant profile") {RecordFields(record:$profile,fields:[.init(key:"name",title:"Name"),.init(key:"phone",title:"Phone")]);Button("Save restaurant profile"){save("restaurant_profile",profile)}};Section("Shared notification preferences") {RecordFields(record:$notification,fields:[.init(key:"managerDayOff",title:"Day-off request alerts",kind:.toggle),.init(key:"sound",title:"Web manager sound",kind:.toggle)]);Button("Save shared preferences"){save("notifications",notification)}};Section("Printing & security") {Label("AirPrint / PDF share is built into every native export",systemImage:"printer");Text("The Windows print bridge remains managed by the Windows program. This iPad does not start a desktop bridge.").font(.footnote);Label("Manager token stored in this device's Keychain",systemImage:"lock.shield");Label("App content hidden in the app switcher",systemImage:"eye.slash");Button("Sign out",role:.destructive){store.logout()}};Section("Build") {DetailPair(title:"Interface",value:"Native SwiftUI · 0.2.1 (3)");DetailPair(title:"Server",value:CommandPolicy.origin);Text("No simulator verification. Physical iPad testing is the next verification step.").font(.footnote)}}.disabled(store.saving).task(id:store.data["/api/settings"]) {store.theme=theme;let settings=store.data["/api/settings"]?["settings"] ?? .null;profile=settings["restaurant_profile"];notification=settings["notifications"]} }
    private func save(_ key:String,_ value:J){guard !value.isNull else {store.error="Wait for the existing settings to load before saving.";return};Task {do {_ = try await store.send("/api/settings/\(key)",method:"PUT",body:.object(["value":value,"updated_by":.s(store.manager.displayName)]));await store.load()}catch {store.report(error)}}}
}
struct NativeWatchdog:View {
    @EnvironmentObject var store:NativeStore
    var body:some View {NativeScreen(title:"HOP Watchdog",subtitle:"Read-only health checks reported by the existing server. No simulated success metrics.") {let value=store.data["/api/command/v2/watchdog"] ?? .null;let checks=value.list("checks");if checks.isEmpty {NativeEmpty(title:"No diagnostics returned",detail:"Refresh to request current health checks.",icon:"waveform.path.ecg")};ForEach(Array(checks.enumerated()),id:\.offset){_,check in HOPPanel {HStack {Image(systemName:"waveform.path.ecg").font(.title2);Text(check.first("name","label","id")).font(.headline);Spacer();StatusTag(value:check.statusText)};Text(check.first("message","summary","detail"));if check["latency_ms"].number>0 {Text("\(check["latency_ms"].int) ms").font(.caption).foregroundStyle(.secondary)}}}} }
}
